import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function downloadInvestigationReport(report, result) {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("FraudLens AI", 14, 18);

    doc.setFontSize(12);
    doc.text("Fraud Investigation Report", 14, 28);

    autoTable(doc, {
        startY: 36,
        head: [["Case Information", ""]],
        body: [
            ["Case ID", report.case_id],
            ["Status", report.status],
            ["Generated At", report.generated_at],
            ["Generated By", report.generated_by],
        ],
    });

    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Invoice Details", ""]],
        body: [
            ["Vendor", result.vendor],
            ["Invoice Number", result.invoice_number],
            ["Invoice Date", result.invoice_date],
            ["Invoice Amount", result.invoice_amount],
        ],
    });

    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Fraud Assessment", ""]],
        body: [
            ["Decision", result.decision],
            ["Risk Score", result.risk_score],
        ],
    });

    autoTable(doc, {
        startY: doc.lastAutoTable.finalY + 10,
        head: [["Fraud Signals"]],
        body: result.signals.map(signal => [
            `${signal.severity.toUpperCase()} - ${signal.title}\n${signal.description}`
        ]),
    });

    doc.text("AI Summary", 14, doc.lastAutoTable.finalY + 15);

    doc.setFontSize(11);

    doc.text(
        report.summary || "",
        14,
        doc.lastAutoTable.finalY + 25,
        { maxWidth: 180 }
    );

    doc.text(
        "Recommended Actions",
        14,
        doc.lastAutoTable.finalY + 50
    );

    report.recommended_actions.forEach((action, index) => {
        doc.text(
            `${index + 1}. ${action}`,
            18,
            doc.lastAutoTable.finalY + 60 + (index * 8)
        );
    });

    doc.save(`${report.case_id}.pdf`);
}